from functions.get_blog_structure import get_structure
from functions.get_blog_structure_meta import get_structure_meta
from functions.get_home_page import get_home_page
from functions.get_article import get_article
from functions.get_article_page import get_article_page
from functions.get_section_page import get_section_page
from functions.get_section_structure import get_section_structure